### ISSUE TITLE
Status Query

### ISSUE THREAD

**Issue by kenrector** [padarom/bevel-gear#1]
I couldn't get this to work on my Mac and I wonder if there is an example that works.  Also,
it appears to me that the shaft angle is always 90˚ but the readme says it works for angles less than 90˚ (Currently this add-in only supports pitch angles of less than 90°).  Unless pitch angle is something different than shaft angle.

is there any plan for further work on this?

**Comment by MrMashley** [comment]
Unable to make this work on Mac, See images for error messages.

<img width="419" alt="Screenshot 2019-12-09 at 19 28 51" src="https://user-images.githubusercontent.com/45629846/70466098-4c9fc600-1aba-11ea-8f2c-1d6773ded281.png">
<img width="420" alt="Screenshot 2019-12-09 at 19 29 47" src="https://user-images.githubusercontent.com/45629846/70466105-4f9ab680-1aba-11ea-8895-831bd9cebc2f.png">

**Comment by eric20136065** [comment]
i´ve got windows and i have the same issue. hope it gets corrected

**Comment by ksharatreddy** [comment]
I've run into the same issues as MrMashley on my Mac.

**Comment by puravdatta-sudo** [comment]
Same issues on my mac

**Comment by padarom** [comment]
Hey there, I'm sorry I've never gotten a notification for this. The short description of the GitHub repo says that it's a work in progress, unfortunately the readme so far hasn't reflected that, so I see the confusion in thinking this is a finished product. Unfortunately it's not yet. I haven't had the time or need for the plugin in a while, but I have started rewriting the code to work more reliably and am planning to finish it this time. It will likely still take some time though.
